name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 17
        uses: actions/setup-node@v1
        with:
          node-version: 17

      # Create a env file with a Hawk token to send a release info
      - name: install modules
        run: npm install

      - name: build project
        run: npm run build:prod

      - name: linting typescript
        run: npm run eslint

      - name: linting styles
        run: npm run stylelint

      - name: testing
        run: npm run test
        if: always()

      - name: build storybook
        run: npm run build-storybook
        if: always()

      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()

      
# jobs:
#   pipeline:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [ 17.x ]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Staring Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#           name: install modules
#           run: npm install
#           - name: build project
#           run: npm build
