name: linting, testing, building
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v2
      - run: npm install 
        name: building
      - run: npm run build:prod
        name: eslint
      - run: npm run eslint
        name: styleling
      - run: npm run stylelint
        name: testing
      - run: npm run test
        name: build storybook
      - run: npm run build-storybook
        name: screenshot testing
      - run: npm run test:ui:ci